# For an explanation of the configuration and more config values, visit https://github.com/probe-rs/cargo-embed/blob/master/src/config/default.toml

[default.reset]
halt_afterwards = false

[default.general]
chip = "STM32F446RETx"
log_level = "WARN"

[default.gdb]
enabled = true
gdb_connection_string = "127.0.0.1:3333"
